
Training model:
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
DeepfakeDetector                         [32, 1]                   --
├─Conv3d: 1-1                            [32, 32, 8, 254, 254]     2,624
├─ReLU: 1-2                              [32, 32, 8, 254, 254]     --
├─MaxPool3d: 1-3                         [32, 32, 4, 127, 127]     --
├─Conv3d: 1-4                            [32, 64, 2, 125, 125]     55,360
├─ReLU: 1-5                              [32, 64, 2, 125, 125]     --
├─MaxPool3d: 1-6                         [32, 64, 1, 62, 62]       --
├─Flatten: 1-7                           [32, 246016]              --
├─Linear: 1-8                            [32, 1]                   246,017
├─Sigmoid: 1-9                           [32, 1]                   --
==========================================================================================
Total params: 304,001
Trainable params: 304,001
Non-trainable params: 0
Total mult-adds (G): 98.71
==========================================================================================
Input size (MB): 251.66
Forward/backward pass size (MB): 4740.12
Params size (MB): 1.22
Estimated Total Size (MB): 4993.00
==========================================================================================
Training...
/raid/home/automathon_2024/account13/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py:605: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv3d(
  0%|          | 1/310 [00:01<06:22,  1.24s/it]
Traceback (most recent call last):
  File "/raid/home/automathon_2024/account13/automathon-2024/run.py", line 295, in <module>
    loss.backward()
  File "/raid/home/automathon_2024/account13/.local/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/raid/home/automathon_2024/account13/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/raid/home/automathon_2024/account13/.local/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.97 GiB. GPU